In [31]:
import numpy as np
import pandas as pd

# Trabajo Práctico 1 - Matrices de Insumo Producto

### Consigna 1

Tenemos que:

$$
\begin{aligned}
& p = Ap + d \\
& p - Ap = d \\
& (I-A)p = d \\
& p = (I-A)^{-1}d
\end{aligned}
$$

De esta manera:

- **a. Si $(I-A)$ es inversible:**

$$
p = (I-A)^{-1}d
$$

Nos encontramos con un sistema de ecuaciones lineales de unica solucion, de manera que podriamos obtener los valores de salida (output) totales, dado el vector de demanda externa.

- **b. Si $(I-A)$ es inversible y $d=\vec{0}$:**

$$
p = \vec{0}
$$

Lo cual nos dice que la produccion total necesaria para cubrir la demanda externa es 0.

- ***ANTIGUO*** c. $(I-A)$ no es inversible:

Algunos cambios en los coeficientes tecnicos $a_{ij}$ que hagan que la matriz en cuestion tenga filas o columnas linealmente dependientes entre si puede provocar que el sistema sea compatible indeterminado, lo que implica que habria mas de un plan de produccion posible para satisfacer ambas demandas. 

- **NUEVO** **c) Cuando $(I-A)$ no es inversible:**

Cuando $(\mathbf{I} - \mathbf{A})$ no es inversible, esto implica que la matriz tiene filas o columnas linealmente dependientes, lo que significa que el sistema puede ser compatible indeterminado (infinitas soluciones) o incompatible (sin solución). Es mas, existe un vector no nulo $v$ tal que $(I-A)v = 0$

En este caso, pueden ocurrir dos situaciones:
   
   - a) El sistema puede ser **compatible indeterminado**:

      - **Condición para que exista solución:** El sistema tendrá solución si y solo si $d$ puede ser expresado como una combinación lineal de las columnas de $(I-A)$
      - Si encontramos una solución particular $p_0$, todas las soluciones serán de la forma $p = p_0 + v$, donde $v$ es cualquier vector que cumpla $(I-A)v = 0$ (Esto es valido pues las matrices son distributivas respecto a la suma)
   
   - b) El sistema puede ser **incompatible**:

      - Esto ocurre cuando $d$ no puede ser expresado como combinación lineal de las columnas de $(I-A)$
      - En términos económicos, no existiría ningún plan de producción que satisfaga la demanda externa $d$

En el contexto del problema, esto significa que cuando $(I-A)$ no es inversible, debemos analizar cuidadosamente el vector de demanda externa $d$. Si bien no podemos usar el método de la matriz inversa, el sistema aún podría tener solución (posiblemente infinitas soluciones).

- **d. $(I-A)$ no es inversible y $d=\vec{0}$:**

Cuando $(\mathbf{I} - \mathbf{A})$ no es inversible, esto implica que la matriz tiene filas o columnas linealmente dependientes, lo que significa que el sistema puede ser compatible indeterminado (infinitas soluciones) o incompatible (sin solución)

Sin embargo, al tener $\mathbf{d} = \vec{0}$, estamos tratando con un sistema homogéneo:

$(\mathbf{I} - \mathbf{A})\mathbf{p} = \vec{0}.$

En este caso, la solución trivial $\mathbf{p} = \vec{0}$ siempre existe, pero debido a la no invertibilidad de $(\mathbf{I} - \mathbf{A})$ es posible que existan otras soluciones no triviales (infinitas soluciones) si el sistema es compatible indeterminado. Esto se debe a la dependencia lineal en $(\mathbf{I} - \mathbf{A})$ (es decir, su determinante es 0), lo que permite la existencia de múltiples planes de producción posibles incluso cuando no hay demanda externa.

En resumen, la producción total necesaria para satisfacer la demanda externa puede ser $\mathbf{p} = \vec{0}$, pero también puede haber infinitos planes de producción debido a la singularidad de $(\mathbf{I} - \mathbf{A})$


---

### Consigna 2

Las funciones estan en el archivo `funciones.py`. Ejecutamos el siguiente codigo para importar las funciones que usaremos en el ejercicio 3

In [32]:
from funciones import calcularLU, inversaLU

### Consigna 3 -  

Tenemos que resolver el siguiente sistema usando lo que hicimos en la consigna 2.

$\mathbf{A} = 
\begin{pmatrix}
0.3 & 0.0 & 0.1 \\
0.05 & 1.0 & 0.2 \\
0.1 & 0.15 & 0.1
\end{pmatrix}, \quad
\mathbf{d} = 
\begin{pmatrix}
100 \\
100 \\
300
\end{pmatrix}$

respondiendo lo siguiente:

-  ¿Hay una justificación económica de los valores encontrados para $\mathbf{p}$?
- ¿Cuál es la característica de la matriz que lleva a esta solución?



In [8]:
A = np.array([[0.3, 0.0, 0.1],
             [0.05, 1.0, 0.2],
             [0.1, 0.15, 0.1]])

d = np.array([100,100,300])
I = np.eye(3)
P,L,U = calcularLU(I-A)
Lontief = inversaLU(L,U,P)
print("La matriz de Leontief queda:\n",Lontief)

print("\nInversa con numpy:\n",np.linalg.inv(I-A))

La matriz de Leontief queda:
 [[  1.37931034  -0.68965517   0.        ]
 [ -2.98850575 -28.50574713  -6.66666667]
 [ -0.34482759  -4.82758621   0.        ]]

Inversa con numpy:
 [[  1.37931034  -0.68965517   0.        ]
 [ -2.98850575 -28.50574713  -6.66666667]
 [ -0.34482759  -4.82758621  -0.        ]]


In [9]:
# Calculamos el vector producto, multiplicacndo la matriz de Leontief por el vector d
Lontief@d

array([   68.96551724, -5149.42528736,  -517.24137931])

1. **Incoherencia de los Valores Negativos en el Vector  $p$:**
   - El vector de producción $p$ obtenido al resolver el sistema $ p = (I - A)^{-1} \cdot d $ contiene valores negativos, lo cual no tiene sentido económico. En un modelo de producción, los valores negativos indican que un sector debería reducir su producción para satisfacer la demanda, lo cual es imposible y sugiere una inestabilidad en el sistema económico modelado.

**NUEVO**
2. **Error en la Estructura de la Matriz $A$:**
   - Analizando la matriz $\mathbf{A}$, observamos que el coeficiente de producción para el segundo sector es ($a_{22} = 1.0$), Esto significa que, para producir una unidad de output del sector 2, se requiere exactamente una unidad de insumo del propio sector 2. Adicionalmente, se necesitan $ a_{12} = 0.0 $ unidades del sector 1 y $a_{32} = 0.15$ unidades del sector 3. Esto implica que el sector 2 consume toda su producción y más, sin generar un output neto para satisfacer la demanda final o para ser utilizado por otros sectores, lo cual es insostenible desde el punto de vista económico.

3. **Dependencia Interna Intensa:**
   - La matriz $A$ muestra una alta interdependencia entre los sectores económicos, especialmente en el segundo sector, que depende completamente de su propia producción para operar. Esto genera una retroalimentación negativa exagerada y amplifica las demandas internas, causando inestabilidad y sensibilidad extrema en la producción. Esta dependencia intensa es una de las razones clave por las cuales el modelo arroja resultados no realistas y no interpretables económicamente.

**NUEVO** 
En conclusión, la estructura interna de la matriz $A$ lleva a un modelo matemáticamente inestable y conduce a un modelo económicamente inviable (especificamente el coeficiente $a_{22} = 1.0$), pues la dependencia total del sector 2 de su propia produccion significa que no puede satisfacer la demanda final ni contribuir al sistema economigo general. Resultando en valores negativos en el vector de produccion $p$
Y cuando nos referimos a que es un modelo "matematicamente inestable" (especialmente en este contexto del modelo de insumo-producto de Leontief), estamos indicando que el sistema presenta caracteristicas matematicas que impiden obtener soluciones viables y unicas. Es decir, la Singularidad de la matriz $I-A$.

---

### Consigna 4 -  

Dado un cambio en la demanda externa:

$$
d^{\prime} = d + \Delta d
$$

Con:

$$
\Delta d = \left(\begin{array}{lll}
0 \\
0 \\
1
\end{array}\right)
$$

Podemos plantear:

$$
p + \Delta p = (I-A)^{-1}(d + \Delta d) = (I-A)^{-1}d + (I-A)^{-1}\Delta d
$$

Y como:

$$
p + \Delta p = (I-A)^{-1}d+\Delta p
$$

Nos queda:

$$
\begin{aligned}
& \Delta p = (I-A)^{-1}\Delta d \\
& \Delta p = L(\Delta d)
\end{aligned}
$$

Con esto, podemos ver que:

$$
\left(\begin{array}{l}
\Delta p_1 \\
\Delta p_2 \\
\Delta p_3
\end{array}\right)=\left(\begin{array}{lll}
L_{11} & L_{12} & L_{13} \\
L_{21} & L_{22} & L_{23} \\
L_{31} & L_{32} & L_{33}
\end{array}\right)\left(\begin{array}{l}
0 \\
0 \\
1
\end{array}\right)=\left(\begin{array}{l}
L_{13} \\
L_{23} \\
L_{33}
\end{array}\right)
$$

Lo cual nos muestra el incremento de las salidas (outputs) de las distintas industrias debido al incremento de una unidad en la demanda total de la industria 3.

---

### Consigna 5 -  

Tenemos los coeficientes tecnicos $a_{ij}$ definidos como:

$$
a_{ij} = \frac{z_{ij}}{p_j}
$$

De manera que, de acuerdo a la economia dada con tres sectores, tenemos:

$$
\begin{aligned}
& Z = \left(\begin{array}{lll}
z_{11} & z_{12} & z_{13} \\
z_{21} & z_{22} & z_{23} \\
z_{31} & z_{32} & z_{33}
\end{array}\right) = \left(\begin{array}{lll}
350 & 0 & 0 \\
50 & 250 & 150 \\
200 & 150 & 550
\end{array}\right) \\
& \\
& P = \left(\begin{array}{lll}
p_{1} & 0 & 0 \\
0 & p_{2} & 0 \\
0 & 0 & p_{3}
\end{array}\right) = \left(\begin{array}{lll}
1000 & 0 & 0 \\
0 & 500 & 0 \\
0 & 0 & 1000
\end{array}\right)
\end{aligned}
$$

Donde la inversa de $P$ es:

$$
P^{-1} = \left(\begin{array}{lll}
\frac{1}{p_{1}} & 0 & 0 \\
0 & \frac{1}{p_{2}} & 0 \\
0 & 0 & \frac{1}{p_{3}}
\end{array}\right) = \left(\begin{array}{lll}
\frac{1}{1000} & 0 & 0 \\
0 & \frac{1}{500} & 0 \\
0 & 0 & \frac{1}{1000}
\end{array}\right)
$$

Asi, nos queda la siguiente matriz de coeficientes $A$:

$$
A = ZP^{-1} = \left(\begin{array}{lll}
\frac{7}{20} & 0 & 0 \\
\frac{1}{20} & \frac{1}{2} & \frac{3}{20} \\
\frac{1}{5} & \frac{3}{10} & \frac{11}{20}
\end{array}\right)
$$

Veamos ahora de obtener la matriz de Leontief $L$. Sabemos que:

$$
L = (I-A)^{-1}
$$

Siendo:

$$
I_3-A = \left(\begin{array}{lll}
1 & 0 & 0 \\
0 & 1 & 0 \\
0 & 0 & 1
\end{array}\right) - \left(\begin{array}{lll}
\frac{7}{20} & 0 & 0 \\
\frac{1}{20} & \frac{1}{2} & \frac{3}{20} \\
\frac{1}{5} & \frac{3}{10} & \frac{11}{20}
\end{array}\right) = \left(\begin{array}{lll}
\frac{13}{20} & 0 & 0 \\
-\frac{1}{20} & \frac{1}{2} & -\frac{3}{20} \\
-\frac{1}{5} & -\frac{3}{10} & \frac{9}{20}
\end{array}\right)
$$

Si ahora calculamos la inversa nos queda:

$$
(I_3-A)^{-1} = \left(\begin{matrix}
\frac{13}{20} & 0 & 0 & | & 1 & 0 & 0 \\
\frac{-1}{20} & \frac{1}{2} & \frac{-3}{20} & | & 0 & 1 & 0 \\
\frac{-1}{5} & \frac{-3}{10} & \frac{9}{20} & | & 0 & 0 & 1
\end{matrix}\right) \sim \cdots \sim \left(\begin{matrix}
1 & 0 & 0 & | & \frac{20}{13} & 0 & 0 \\
0 & 1 & 0 & | & \frac{35}{78} & \frac{5}{2} & \frac{5}{6} \\
0 & 0 & 1 & | & \frac{115}{117} & \frac{5}{3} & \frac{25}{9}
\end{matrix}\right)
$$

Es decir:

$$
L = \left(\begin{matrix}
\frac{20}{13} & 0 & 0 \\
\frac{35}{78} & \frac{5}{2} & \frac{5}{6} \\
\frac{115}{117} & \frac{5}{3} & \frac{25}{9}
\end{matrix}\right)
$$

In [13]:
A = np.array([[7/20,0,0],
              [1/20,1/2,3/20],
              [1/5, 3/10, 11/20]])
I = np.eye(3)
P,L,U = calcularLU(I-A)
lontief = inversaLU(L,U,P)
print("Con nuestro algoritmo:\n",lontief)

lontief_a_mano = np.array([[20/13,0,0],
                           [35/78,5/2,5/6],
                           [115/117, 5/3, 25/9]])
print("\nHecho a mano:\n",lontief_a_mano)

Con nuestro algoritmo:
 [[1.53846154 0.         0.        ]
 [0.44871795 2.5        0.83333333]
 [0.98290598 1.66666667 2.77777778]]

Hecho a mano:
 [[1.53846154 0.         0.        ]
 [0.44871795 2.5        0.83333333]
 [0.98290598 1.66666667 2.77777778]]


---

### Consigna 6 -  

A partir de la siguiente fórmula:

$$
\begin{aligned} \\
\left(\left(\begin{array}{ll}
I_{n \times n} & 0_{n \times n} \\
0_{m \times n} & I_{m \times m}
\end{array}\right)-
\left(\begin{array}{ll}
A^{rr} & A^{rs} \\
A^{sr} & A^{ss} \\
\end{array}\right)\right)
\left(\begin{array}{l}
p^r \\
p^s
\end{array}\right)=
\left(\begin{array}{l}
d^r \\
d^s
\end{array}\right)
\end{aligned}
$$

$$\begin{aligned} \\
\end{aligned}$$

**Condiciones para la multiplicación en bloques:**

- **Compatibilidad de dimensiones:** Los submatrices y subvectores deben tener dimensiones compatibles para las operaciones de suma y multiplicación.
- **Asociatividad de la multiplicación:** Aunque la multiplicación de matrices no es conmutativa, sí es asociativa, lo que permite agrupar operaciones en bloques bajo ciertas condiciones.
- **No siempre es posible:** La multiplicación en bloques no siempre es aplicable; depende de la estructura específica de las matrices involucradas.

En nuestro caso, las matrices y vectores están particionados como:

- $ A^{rr} \in \mathbb{R}^{n \times n} $
- $ A^{rs} \in \mathbb{R}^{n \times m} $
- $ A^{sr} \in \mathbb{R}^{m \times n} $
- $ A^{ss} \in \mathbb{R}^{m \times m} $

Vectores:

- $ \Delta p^r \in \mathbb{R}^{n \times 1} $
- $ \Delta p^s \in \mathbb{R}^{m \times 1} $
- $ \Delta d^r \in \mathbb{R}^{n \times 1} $
- $ \Delta d^s \in \mathbb{R}^{m \times 1} $

Dado que las dimensiones son compatibles, la multiplicación en bloques es realizable en este contexto.

Tenemos que deducir cómo calcular la variación de la producción en la región r ($\Delta p^r$) para cubrir una variación de la demanda, considerando las relaciones inter-regionales.

Entonces, resolvamos la siguiente fórmula:

$$
\begin{aligned} \\
\left(\left(\begin{array}{ll}
I_{n \times n} & 0_{n \times n} \\
0_{m \times n} & I_{m \times m}
\end{array}\right)-
\left(\begin{array}{ll}
A^{rr} & A^{rs} \\
A^{sr} & A^{ss} \\
\end{array}\right)\right)
\left(\begin{array}{l}
\Delta p^r \\
\Delta p^s
\end{array}\right)=
\left(\begin{array}{l}
\Delta d^r \\
\Delta d^s
\end{array}\right)
\end{aligned}
$$

$$
\begin{aligned} \\
\left(\begin{array}{ll}
(I - A^{rr}) & - A^{rs} \\
- A^{sr} &  (I - A^{ss})
\end{array}\right)
\left(\begin{array}{l}
\Delta p^r \\
\Delta p^s
\end{array}\right)=
\left(\begin{array}{l}
\Delta d^r \\
\Delta d^s
\end{array}\right)
\end{aligned}
$$

**Recordatorio:** La multiplicación de matrices **no es conmutativa**. Es decir, en general, $ AB \neq BA $. Por lo tanto, el orden en el que se multiplican las matrices y vectores es crucial.

- **Primera ecuación:**

  $$
  (I - A^{rr}) \Delta p^r - A^{rs} \Delta p^s = \Delta d^r
  $$

- **Segunda ecuación:**

  $$
  -A^{sr} \Delta p^r + (I - A^{ss}) \Delta p^s = \Delta d^s
  $$

Por simplicidad, la consigna nos dice que fijemos $\Delta d^s = 0$. 


- La segunda ecuación se convierte en:

  $$
  -A^{sr} \Delta p^r + (I - A^{ss}) \Delta p^s = 0 
  $$

Entonces, nos queda el siguiente sistema de ecuaciones a resolver:
### CORREGIR A PARTIR DE ACA, OJO CON el menos en $(2)$

$$
\\ (I - A^{rr}) \Delta p^r - A^{rs} \Delta p^s = \Delta d^r \quad \quad (1)
\\ -A^{sr} \Delta p^r + (I - A^{ss}) \Delta p^s = 0  \quad \quad (2)
$$

$$\begin{aligned} \\
\end{aligned}$$

De la ecuación (2), podemos sacar facilmente que: 

$$
\begin{aligned} \\
& \Delta p^s (I - A^{ss}) = - (\Delta p^r A^{sr}) \hspace{10 mm} \Longrightarrow \hspace{10 mm} \Delta p^s = - \Delta p^r A^{sr} (I - A^{ss})^{-1}
\end {aligned}
$$

$$\begin{aligned} \\
\end{aligned}$$

Ahora bien, reemplazando el valor que obtuvimos de $\Delta p^s$ en la ecuación (1), tenemos que:

$$
\begin{aligned} \\
& \Delta p^r (I - A^{rr}) - \Delta p^r A^{sr} (I - A^{ss})^{-1} A^{rs} = \Delta d^r
\end {aligned}
$$

$$
\begin{aligned} \\
& \Delta p^r (I - A^{rr} - A^{sr} (I - A^{ss})^{-1} A^{rs}) = \Delta d^r
\end {aligned}
$$

$$
\begin{aligned} \\
& \Delta p^r = (I - A^{rr} - A^{sr} (I - A^{ss})^{-1} A^{rs})^{-1} \Delta d^r \longrightarrow \text{Fórmula que buscabamos}
\end {aligned}
$$




---

### Consigna 7 -  

En primer lugar, vamos a leer el archivo de excel denominado "MIP_Latinoamericana_2011.xlsx", el cual, en la hoja "LAT_IOT_2011", nos provee información sobre los flujos entre 40 sectores de 18 países, expresados en millones de dólares.

In [18]:
# Leemos el archivo completo.
MIP_Latinoamericana_2011 = pd.read_excel("MIP_Latinoamericana_2011.xlsx", engine = "openpyxl", sheet_name = None)

# Seleccionamos la hoja "LAT_IOT_2011".
LAT_IOT_2011 = MIP_Latinoamericana_2011["LAC_IOT_2011"]
LAT_IOT_2011.head()

Country_iso3 Nosector                                  Sector        ARGs1  \
0          ARG      s01                Agriculture and forestry  9725.566485   
1          ARG      s02                     Hunting and fishing    13.820241   
2          ARG      s03           Mining and quarrying (energy)     6.095956   
3          ARG      s04       Mining and quarrying (non-energy)     0.000000   
4          ARG      s05  Meat and meat products; dairy products    23.017536   

       ARGs2        ARGs3       ARGs4         ARGs5        ARGs6       ARGs7  \
0  18.369597     0.000000    0.000000  11890.682268  2331.532300  594.552280   
1   0.062689     0.000000    0.000000      1.253285     2.774203    0.445318   
2   0.140437  2238.394196   47.503210      0.522333     0.618710    0.165520   
3   0.687199   295.194361  470.706336      1.140358    13.123509    1.914597   
4   0.009325     0.505593    0.040398    356.730934    88.047795   15.017792   

   ...   EXP_MDV   EXP_NPL     EXP_TUR   EXP_PAK  EXP_LKA    EXP_CUB  \
0  ...  0.000000  0.865281  132.020508  2.572569      0.0  30.970039   
1  ...  0.000000  0.000000    0.161072  0.000000      0.0   0.000000   
2  ...  0.000000  0.000000    0.000000  0.000000      0.0   0.000000   
3  ...  0.000000  0.000000    0.000000  0.000000      0.0   0.019760   
4  ...  0.035902  0.000000    0.131605  0.547536      0.0   3.120524   

    EXP_SUR      EXP_ROW   Adjustment        Output  
0  0.011896  2403.097412 -1695.114624  64585.080680  
1  0.000000     0.815166     5.434752   1430.287291  
2  0.000000     0.000000  1847.147827  23964.065765  
3  0.000000     0.432800   355.133514   7486.322979  
4  0.039276   414.973785   -30.369465  17628.831707  

[5 rows x 798 columns]

En segundo lugar, vamos a seleccionar los dos países que nos fueron asignados para la realización de esta consigna, los cuales son: Brasil (BRA) y Guatemala (GTM). Además, vamos a generar la matriz de Insumo-Producto de las regiones mencionadas.

In [19]:
# Seleccionamos las filas correspondientes.
M_insumo_producto = LAT_IOT_2011[(LAT_IOT_2011["Country_iso3"] == "BRA") | (LAT_IOT_2011["Country_iso3"] == "GTM")]

# Seleccionamos las columnas correspondientes y me guardo los datos de los outputs en una variable.
outputs = M_insumo_producto["Output"].to_numpy()
sectores_BRA = []
sectores_GTM = []

for sector in range(40):
    sector_bra = "BRAs" + str(sector + 1)
    sector_gtm = "GTMs" + str(sector + 1)

    sectores_BRA.append(sector_bra)
    sectores_GTM.append(sector_gtm)

M_insumo_producto = M_insumo_producto[sectores_BRA + sectores_GTM]

# Acomodamos los índices.
M_insumo_producto = M_insumo_producto.reset_index().drop(columns = ["index"])
M_insumo_producto

BRAs1         BRAs2        BRAs3        BRAs4         BRAs5  \
0   8759.594677  1.838029e+02    12.237987    14.005361  29373.005548   
1    183.802943  3.856745e+00     0.256790     0.293875    616.335010   
2     28.515684  5.983458e-01  4234.896096    97.541854      4.406442   
3    322.237628  6.761526e+00   226.599170  1072.567732     35.324905   
4    745.918167  1.565163e+01     2.192449     1.237900   3554.205906   
..          ...           ...          ...          ...           ...   
75     0.000054  1.133000e-06     0.001167     0.000644      0.000173   
76     0.000000  0.000000e+00     0.023561     0.000000      0.011780   
77     0.002757  5.785900e-05     0.004462     0.002624      0.001858   
78     0.006531  1.370320e-04     0.106584     0.027085      0.004202   
79     0.000009  1.840000e-07     0.000373     0.000189      0.000953   

          BRAs6         BRAs7         BRAs8        BRAs9       BRAs10  ...  \
0   9446.762361  15538.555687  23421.869850  1013.335027  2589.431793  ...   
1    198.221812    326.046167    491.462079    21.262851    54.334156  ...   
2    149.753630      3.314964     25.225517    38.806077     0.140032  ...   
3    124.788515     10.128543     23.269877     7.144141     0.421785  ...   
4    309.467144      0.527286    337.183320    13.018326     0.280040  ...   
..          ...           ...           ...          ...          ...  ...   
75     0.000048      0.000195      0.000109     0.000010     0.000005  ...   
76     0.023561      0.011780      0.035341     0.023561     0.000000  ...   
77     0.001360      0.001398      0.001762     0.001092     0.000326  ...   
78     0.009390      0.006964      0.007220     0.006135     0.001480  ...   
79     0.000755      0.000153      0.000535     0.000130     0.000108  ...   

    GTMs31  GTMs32     GTMs33      GTMs34      GTMs35        GTMs36  \
0      0.0     0.0   0.004689    0.000000    0.004131  8.510000e-07   
1      0.0     0.0   0.000000    0.000000    0.000000  0.000000e+00   
2      0.0     0.0   0.000000    0.000000    0.000000  0.000000e+00   
3      0.0     0.0   0.009515    0.002041    0.144269  3.795410e-04   
4      0.0     0.0   0.000000    0.000000    0.000000  0.000000e+00   
..     ...     ...        ...         ...         ...           ...   
75     0.0     0.0  16.806559    8.178785   92.340199  7.568810e+01   
76     0.0     0.0   4.466365    2.599111    3.444560  1.319104e+02   
77     0.0     0.0  10.281294  144.922489   35.704073  4.839859e+01   
78     0.0     0.0  25.865526   78.384191  133.583750  1.278951e+02   
79     0.0     0.0  45.672561   42.266268  230.543176  1.523792e+02   

        GTMs37      GTMs38      GTMs39       GTMs40  
0     0.000000    0.000000    0.000002     0.224915  
1     0.000000    0.000000    0.000000     0.000000  
2     0.000000    0.000000    0.000000     0.000000  
3     0.000000    0.000000    0.013251     0.016241  
4     0.000000    0.000000    0.000000     0.000000  
..         ...         ...         ...          ...  
75   77.970900   13.410398   24.730000   231.419357  
76  226.515475   35.006654   41.728949   248.777502  
77  208.087697  278.317289   41.882683   900.512152  
78  479.048110  304.339726  646.656267  1319.427678  
79  157.546918   36.584185  109.321822  1132.678517  

[80 rows x 80 columns]

En tercer lugar, debemos calcular los coeficientes técnicos para cada bloque en sus submatrices intra-regionales e inter-regionales de la A total.

In [20]:
M_coeficientes_tecnicos = M_insumo_producto.to_numpy() # Convertimos nuestro DataFrame en una matriz

cant_filas = M_coeficientes_tecnicos.shape[0]
cant_columnas = M_coeficientes_tecnicos.shape[1]

for fila in range(cant_filas):
    for columna in range(cant_columnas):
        monto = M_coeficientes_tecnicos[fila][columna]
        total_producido = outputs[columna]


        if (total_producido > 0):
            M_coeficientes_tecnicos[fila][columna] = monto / total_producido
        else:
            M_coeficientes_tecnicos[fila][columna] = 0

M_coeficientes_tecnicos

array([[4.61047789e-02, 4.61047789e-02, 1.28969429e-04, ...,
        0.00000000e+00, 2.11560849e-10, 9.61656254e-06],
       [9.67418512e-04, 9.67418512e-04, 2.70617094e-06, ...,
        0.00000000e+00, 0.00000000e+00, 0.00000000e+00],
       [1.50087913e-04, 1.50087913e-04, 4.46292469e-02, ...,
        0.00000000e+00, 0.00000000e+00, 0.00000000e+00],
       ...,
       [1.45133454e-08, 1.45132409e-08, 4.70261640e-08, ...,
        1.22740434e-01, 5.35391897e-03, 3.85027213e-02],
       [3.43730610e-08, 3.43728449e-08, 1.12323319e-06, ...,
        1.34216563e-01, 8.26629296e-02, 5.64140706e-02],
       [4.63437628e-11, 4.61542082e-11, 3.93179085e-09, ...,
        1.61339556e-02, 1.39747537e-02, 4.84293356e-02]])

Bien, ahora veamos de simular los shocks correspondientes a cada sector de Brasil:

In [21]:
outputs_shock = outputs.copy() #veamos de copiar el array de outputs para no modificar los valores originales
M_coeficientes_tecnicos_shock = M_coeficientes_tecnicos.copy() # Copiamos la matriz anterior

sector_negativo = 4 #sector BRAs05
outputs_shock[sector_negativo] *= 0.9 #aplicamos shock negativo del 10%

sectores_positivos = [5, 6, 7] #sector BRAs06, 07 y 08
for sector in sectores_positivos:
    outputs_shock[sector] *= 1.033 #aplicamos shock positivo del 3.3%

#ahora veamos de recalcular los coef. tecnicos $a_{ij}$ para los sectores afectados
for fila in range(cant_filas):
    for columna in [sector_negativo] + sectores_positivos:
        monto = M_coeficientes_tecnicos_shock[fila][columna]
        total_producido = outputs_shock[columna]

        if total_producido > 0:
            M_coeficientes_tecnicos_shock[fila][columna] = monto / total_producido
        else:
            M_coeficientes_tecnicos_shock[fila][columna] = 0

M_coeficientes_tecnicos_shock #simplemente la mostramos para corroborar que hubo cambios en los coeficientes

array([[4.61047789e-02, 4.61047789e-02, 1.28969429e-04, ...,
        0.00000000e+00, 2.11560849e-10, 9.61656254e-06],
       [9.67418512e-04, 9.67418512e-04, 2.70617094e-06, ...,
        0.00000000e+00, 0.00000000e+00, 0.00000000e+00],
       [1.50087913e-04, 1.50087913e-04, 4.46292469e-02, ...,
        0.00000000e+00, 0.00000000e+00, 0.00000000e+00],
       ...,
       [1.45133454e-08, 1.45132409e-08, 4.70261640e-08, ...,
        1.22740434e-01, 5.35391897e-03, 3.85027213e-02],
       [3.43730610e-08, 3.43728449e-08, 1.12323319e-06, ...,
        1.34216563e-01, 8.26629296e-02, 5.64140706e-02],
       [4.63437628e-11, 4.61542082e-11, 3.93179085e-09, ...,
        1.61339556e-02, 1.39747537e-02, 4.84293356e-02]])

Con la variacion que obtuvimos en los outputs de los sectores correspondientes, veamos como se modifica la demanda externa $\Delta d$ cuando se considera el modelo de region simple. Siendo:

$$
(I-A^{rr})\Delta p^r = \Delta d^r
$$

Tenemos que:

In [22]:
# Definimos todas las variables necesarias.
I = np.eye(40)
A_rr = M_coeficientes_tecnicos[:40, :40]
matriz_Leontief_inv = I - A_rr
delta_p = outputs[:40] - outputs_shock[:40]

# Calculamos la demanda externa.
delta_d1 = matriz_Leontief_inv @ delta_p
delta_d1

array([-1.33986335e+03, -2.81144091e+01,  5.44306149e+00,  1.68767836e+00,
        6.79294487e+03, -2.09279931e+03, -9.77114209e+02, -2.30302128e+03,
        5.70723989e+00,  1.36986309e-02,  4.67817791e+00, -1.29511738e-01,
       -3.58294593e-01,  4.88020147e+00,  2.30064480e+01, -5.13070150e+00,
        2.22645550e+01,  1.51994758e+01,  1.98946367e+00,  3.41586893e+01,
        1.63274893e+01,  3.70885042e+00,  8.30963675e+00, -1.11868984e+01,
        7.66195953e-02, -1.36183430e-01,  1.16856365e-01, -2.24416041e-01,
       -4.72971812e-02,  1.37387283e+00,  3.37672546e-02,  8.75977290e-02,
        2.25673800e-01,  5.12312316e+00,  1.71396028e-01,  3.30645908e+01,
        1.71833084e+01, -3.36734255e+01,  1.18576833e+02, -1.46616335e+02])

Ahora nos dirigimos a la ecuación (6), una fórmula completa que considera ambas regiones:  

$$
\Delta \mathbf{p}^r=\left(\mathbf{I}-\mathbf{A}^{r r}-\mathbf{A}^{r s}\left(\mathbf{I}-\mathbf{A}^{s s}\right)^{-1} \mathbf{A}^{s r}\right)^{-1} \Delta \mathbf{d}^r
$$

Donde nos queda:

$$
\left(\mathbf{I}-\mathbf{A}^{r r}-\mathbf{A}^{r s}\left(\mathbf{I}-\mathbf{A}^{s s}\right)^{-1} \mathbf{A}^{s r}\right) \Delta \mathbf{p}^r=\Delta \mathbf{d}^r
$$

In [25]:
# Definimos todas las variables necesarias.
I = np.eye(40)
A_rr = M_coeficientes_tecnicos[:40, :40]
A_rs = M_coeficientes_tecnicos[:40, 40:]
A_sr = M_coeficientes_tecnicos[40:, :40]
A_ss = M_coeficientes_tecnicos[40:, 40:]
delta_p = outputs[:40] - outputs_shock[:40]
P, L, U = calcularLU(I-A_ss)

# Calculamos la demanda externa.
delta_d2 = (I - A_rr - (A_rs @ inversaLU(L, U, P) @ A_sr)) @ delta_p
delta_d2

array([-1.33986335e+03, -2.81144091e+01,  5.44306149e+00,  1.68767840e+00,
        6.79294487e+03, -2.09279931e+03, -9.77114209e+02, -2.30302128e+03,
        5.70723989e+00,  1.36986309e-02,  4.67817792e+00, -1.29511682e-01,
       -3.58294593e-01,  4.88020156e+00,  2.30064509e+01, -5.13070138e+00,
        2.22645658e+01,  1.51994762e+01,  1.98946823e+00,  3.41586936e+01,
        1.63274895e+01,  3.70885284e+00,  8.30963689e+00, -1.11868956e+01,
        7.66204171e-02, -1.36183429e-01,  1.16857483e-01, -2.24416018e-01,
       -4.72971421e-02,  1.37387376e+00,  3.37672546e-02,  8.75977290e-02,
        2.25674074e-01,  5.12312316e+00,  1.71396028e-01,  3.30645916e+01,
        1.71833084e+01, -3.36734255e+01,  1.18576833e+02, -1.46616335e+02])

Si comparamos con los resultados del modelo de region simple, tenemos:

In [26]:
print(delta_d1 - delta_d2)

[-1.27801513e-06  0.00000000e+00  0.00000000e+00 -3.82336487e-08
  0.00000000e+00  0.00000000e+00 -3.81567133e-09 -2.03695436e-07
  0.00000000e+00  0.00000000e+00 -5.80594772e-09 -5.65399481e-08
  0.00000000e+00 -8.23639006e-08 -2.80826097e-06 -1.16684546e-07
 -1.07646692e-05 -3.86749686e-07 -4.55465444e-06 -4.25728184e-06
 -2.22534130e-07 -2.42533939e-06 -1.40395265e-07 -2.77092090e-06
 -8.21745052e-07 -4.40515846e-10 -1.11849836e-06 -2.29520245e-08
 -3.90886877e-08 -9.26977977e-07  0.00000000e+00  0.00000000e+00
 -2.74308101e-07  0.00000000e+00  0.00000000e+00 -8.37727896e-07
 -4.35633751e-11  0.00000000e+00 -2.10903721e-07 -9.27627752e-10]


Y notemos que:

In [29]:
print(A_rs)
print(A_sr)

[[5.84652620e-05 0.00000000e+00 0.00000000e+00 ... 0.00000000e+00
  2.11560849e-10 9.61656254e-06]
 [0.00000000e+00 0.00000000e+00 0.00000000e+00 ... 0.00000000e+00
  0.00000000e+00 0.00000000e+00]
 [0.00000000e+00 0.00000000e+00 0.00000000e+00 ... 0.00000000e+00
  0.00000000e+00 0.00000000e+00]
 ...
 [0.00000000e+00 0.00000000e+00 0.00000000e+00 ... 0.00000000e+00
  0.00000000e+00 0.00000000e+00]
 [2.58580091e-06 0.00000000e+00 3.43348029e-07 ... 5.40275451e-05
  3.32739131e-05 2.26930594e-05]
 [2.43557414e-08 6.57463370e-08 1.09506057e-09 ... 5.00748099e-08
  3.70471808e-08 1.50861717e-07]]
[[9.59823450e-07 9.59823415e-07 0.00000000e+00 ... 0.00000000e+00
  1.95985649e-09 5.28926782e-08]
 [0.00000000e+00 0.00000000e+00 0.00000000e+00 ... 0.00000000e+00
  0.00000000e+00 0.00000000e+00]
 [0.00000000e+00 0.00000000e+00 0.00000000e+00 ... 0.00000000e+00
  0.00000000e+00 0.00000000e+00]
 ...
 [1.45133454e-08 1.45132409e-08 4.70261640e-08 ... 1.57507351e-07
  2.06513635e-08 6.34036031e-08]

#### Analisis
1. **Comparación entre Modelos de Región Simple y Completa:**
   - El modelo de región simple considera solo la matriz intra-regional de Brasil $A^{rr}$, ignorando las interacciones con Guatemala.
   - El modelo completo incorpora las interacciones inter-regionales, incluyendo los efectos de las matrices $A^{rs}$ y $A^{sr}$ que reflejan la conexión entre los países.

2. **Resultados:**
   - Al comparar ambos modelos, se observa que las diferencias en la modificación de la producción $\Delta d_1 - \Delta d_2$ son extremadamente pequeñas, cercanas a cero.
   - Esto indica que las interacciones entre Brasil y Guatemala no afectan significativamente los resultados de los shocks aplicados.

3. **Conclusión y Justificación:**
   - La influencia mínima entre regiones sugiere una baja interdependencia entre los sectores de ambos países en este contexto específico.
   - Los sectores brasileños afectados por los shocks muestran una autosuficiencia alta, con poca dependencia de la producción guatemalteca.
   
   Nota: Notemos mas arriba lo pequeños que son los valores de los coeficientes tecnicos inter-regionales $A^{rs}$ y $A^{sr}$, lo cual refleja una débil conexión entre ambos países en términos de intercambio productivo.