In [1]:
import numpy

In [3]:
# CReamos una matriz de 3x3
A = numpy.array([[1, 0, 1], 
                 [1, 1, 0], 
                 [0, 1, 1]])

# Calculamos la inversa de la matriz
A_inv = numpy.linalg.inv(A)
print(A_inv)

[[ 0.5  0.5 -0.5]
 [-0.5  0.5  0.5]
 [ 0.5 -0.5  0.5]]


In [5]:
v = numpy.array([1, 1,0])

# Multiplicamos la matriz inversa por el vector
numpy.dot(A_inv, v)

array([1., 0., 0.])