In [1]:
import numpy as np

## **Ejercicio 3**. Escribir funciones que calculen la solución de un sistema:

### (a) Ly = b, siendo L triangular inferior.
### (b) Ux = y, siendo U triangular superior

In [17]:
np.zeros(3)

array([0., 0., 0.])

In [21]:
def Ly(L,b):
    """
    Resuelve el sistema Ly = b donde L es una matriz triangular inferior.
    
    Args:
        L (array): Matriz triangular inferior.
        b (array): Vector de términos independientes.
        
    Returns:
        y (array): Solución del sistema Ly = b.
    """
    L = np.array(L)
    b = np.array(b)
    n = len(b)
    y = np.zeros(n)
    
    y[0] = b[0]
    for i in range(1,n):
        y[i] = b[i] - np.dot(L[i,:i],y[:i]) # Similar a como lo hice goatcheverry
    return y
    
def Ux(U,x):
    """
    Calcula el producto matricial de una matriz triangular superior por un vector
    Args:
        U (array): matriz triangular superior
        x (array): vector
    Return:
        y (array): producto matricial de U por x
    """
    U = np.array(U)
    x = np.array(x)
    n = len(x)
    y = np.zeros(n)
    
    for i in range(n-1,-1,-1):
        y[i] = np.dot(U[i,i:],x[i:])
    
    return y

## **Ejercicio 4**. Escribir funciones de Python que realicen las siguientes tareas:


### (a) Calcular la descomposición LU de una matriz dada A, asumiendo que no es necesario realizar pivoteos

In [5]:
# Testeo con la matriz del pdf
A= np.array([[2,1,2,3],
              [4,3,3,3],
              [-2,2,-4,-12],
              [4,1,8,-3]])

n = A.shape[0]
# Sé que la primer fila de L solo tiene 1 en la diagonal, i.e. L[0,0] = 1

L = np.eye(n)
for i in range(n-1):
    L_i = np.eye(n)
    for j in range(i+1,n):
        L[j,i] = -(A[j,i]/A[i,i])
        L_i[j,i] = -(A[j,i]/A[i,i])
    
    print(f"L_{i+1} = \n",L_i)
    A = np.dot(L_i,A)
    print(f"A_{i+1} = \n",A)

print("L = \n",L)
print("U = \n",A)

L_1 = 
 [[ 1.  0.  0.  0.]
 [-2.  1.  0.  0.]
 [ 1.  0.  1.  0.]
 [-2.  0.  0.  1.]]
A_1 = 
 [[ 2.  1.  2.  3.]
 [ 0.  1. -1. -3.]
 [ 0.  3. -2. -9.]
 [ 0. -1.  4. -9.]]
L_2 = 
 [[ 1.  0.  0.  0.]
 [ 0.  1.  0.  0.]
 [ 0. -3.  1.  0.]
 [ 0.  1.  0.  1.]]
A_2 = 
 [[  2.   1.   2.   3.]
 [  0.   1.  -1.  -3.]
 [  0.   0.   1.   0.]
 [  0.   0.   3. -12.]]
L_3 = 
 [[ 1.  0.  0.  0.]
 [ 0.  1.  0.  0.]
 [ 0.  0.  1.  0.]
 [ 0.  0. -3.  1.]]
A_3 = 
 [[  2.   1.   2.   3.]
 [  0.   1.  -1.  -3.]
 [  0.   0.   1.   0.]
 [  0.   0.   0. -12.]]
L = 
 [[ 1.  0.  0.  0.]
 [-2.  1.  0.  0.]
 [ 1. -3.  1.  0.]
 [-2.  1. -3.  1.]]
U = 
 [[  2.   1.   2.   3.]
 [  0.   1.  -1.  -3.]
 [  0.   0.   1.   0.]
 [  0.   0.   0. -12.]]


In [2]:
def descomposicion_LU(A):
    """
    Realiza la descomposición LU de una matriz cuadrada A asumiendo que no es necesario realizar pivoteos
    Args:
        A (array): matriz cuadrada
    Return:
        L (array): matriz triangular inferior
        U (array): matriz triangular superior
    """
    A = np.array(A)
    n = A.shape[0]
    L = np.eye(n)
    U = A.copy()
   
    for i in range(n-1):
        for j in range(i+1, n):
            # Calculamos los factores de la matriz de eliminación de Gauss
            factor = U[j, i] / U[i, i]
            L[j, i] = factor  # Guarda el factor en la columna i de L
            # Actualiza la fila j de U
            U[j, i:] = U[j, i:] - factor * U[i, i:]

    return L, U


In [6]:
A= np.array([[2,1,2,3],
              [4,3,3,3],
              [-2,2,-4,-12],
              [4,1,8,-3]])

L,U = descomposicion_LU(A)
print("\nL = \n",L)
print("\nU = \n",U)

# Nos fijamos si L@U == A
print("\nL@U = \n",L@U)
print("\nA = \n",A)
L@U == A


L = 
 [[ 1.  0.  0.  0.]
 [ 2.  1.  0.  0.]
 [-1.  3.  1.  0.]
 [ 2. -1.  3.  1.]]

U = 
 [[  2   1   2   3]
 [  0   1  -1  -3]
 [  0   0   1   0]
 [  0   0   0 -12]]

L@U = 
 [[  2.   1.   2.   3.]
 [  4.   3.   3.   3.]
 [ -2.   2.  -4. -12.]
 [  4.   1.   8.  -3.]]

A = 
 [[  2   1   2   3]
 [  4   3   3   3]
 [ -2   2  -4 -12]
 [  4   1   8  -3]]


array([[ True,  True,  True,  True],
       [ True,  True,  True,  True],
       [ True,  True,  True,  True],
       [ True,  True,  True,  True]])

### (b) Resolver un sistema $Ax = b$, utilizando la función del ítem anterior y las del ejercicio 3. Aplicar esta función para resolver el ítem c. del ejercicio 2

Sea $\boldsymbol{A}=\left(\begin{array}{cccc}1 & -1 & 0 & 1 \\ 0 & 1 & 4 & 0 \\ 2 & -1 & 0 & -2 \\ -3 & 3 & 0 & -1\end{array}\right) \in \mathbb{R}^{4 \times 4}$ del ejercicio 2 y usando la descomposición LU de A resolvemos el sistema $\boldsymbol{A} \boldsymbol{x}=\boldsymbol{b}$, $\operatorname{para} \boldsymbol{b}=\left(\begin{array}{c}1 \\ -7 \\ -5 \\ 1\end{array}\right)$

In [43]:
A = np.array([[1,-1,0,1],
              [0,1,4,0],
              [2,-1,0,-2],
              [-3,3,0,-1]])

L,U = descomposicion_LU(A)
print("\nL = \n",L)
print("\nU = \n",U)

# Para resolver Ax = b, primero resuelvo Ly = b y luego Ux = y

b = np.array([1,-7,-5,1])

y = Ly(L,b)
print("\ny = ",y)

x = Ux(U,y)
print("\nx = ",x)




L = 
 [[ 1.  0.  0.  0.]
 [ 0.  1.  0.  0.]
 [ 2.  1.  1.  0.]
 [-3.  0. -0.  1.]]

U = 
 [[ 1 -1  0  1]
 [ 0  1  4  0]
 [ 0  0 -4 -4]
 [ 0  0  0  2]]

y =  [ 1. -7.  0.  4.]

x =  [ 12.  -7. -16.   8.]
