In [1]:
import numpy as np

## **Ejercicio 3**. Escribir funciones que calculen la solución de un sistema:

### (a) Ly = b, siendo L triangular inferior.
### (b) Ux = y, siendo U triangular superior

In [2]:
def Ly(L,y):
    """ 
    Calcula el producto matricial de una matriz triangular inferior por un vector
    Args:
        L (array): matriz triangular inferior
        y (array): vector
    Return:
        b (array): producto matricial de L por y
    """
    L = np.array(L)
    y = np.array(y)
    n = len(y)
    b = np.zeros(n)
    
    for i in range(n):
        b[i] = np.dot(L[i,:i+1],y[:i+1])
    
    return b
    
def Ux(U,x):
    """
    Calcula el producto matricial de una matriz triangular superior por un vector
    Args:
        U (array): matriz triangular superior
        x (array): vector
    Return:
        y (array): producto matricial de U por x
    """
    U = np.array(U)
    x = np.array(x)
    n = len(x)
    y = np.zeros(n)
    
    for i in range(n-1,-1,-1):
        y[i] = np.dot(U[i,i:],x[i:])
    
    return y

In [10]:
L = np.array([[1,0,0],
              [2,3,0],
              [4,5,6]])
print("L =\n",L)
y = np.array([1,2,3])
print("\ny = ",y)
print("Producto matricial de L por y",Ly(L,y))

L =
 [[1 0 0]
 [2 3 0]
 [4 5 6]]

y =  [1 2 3]
Producto matricial de L por y [ 1.  8. 32.]


In [11]:
U = np.array([[1,2,3],
              [0,4,5],
              [0,0,6]])

print("U = \n",U)

x = np.array([1,2,3])
print("\nx = ",x)

print("Producto matricial de U por x = ",Ux(U,x))

U = 
 [[1 2 3]
 [0 4 5]
 [0 0 6]]

x =  [1 2 3]
Producto matricial de U por x =  [14. 23. 18.]


## **Ejercicio 4**. Escribir funciones de Python que realicen las siguientes tareas:
### (a) Calcular la descomposición LU de una matriz dada A, asumiendo que no es necesario realizar pivoteos

In [52]:
# Testeo con la matriz del pdf
A= np.array([[2,1,2,3],
              [4,3,3,3],
              [-2,2,-4,-12],
              [4,1,8,-3]])

n = A.shape[0]
# Sé que la primer fila de L solo tiene 1 en la diagonal, i.e. L[0,0] = 1

L = np.eye(n)
for i in range(n-1):
    L_i = np.eye(n)
    for j in range(i+1,n):
        L[j,i] = -(A[j,i]/A[i,i])
        L_i[j,i] = -(A[j,i]/A[i,i])
    print("L = \n",L)
    A = np.dot(L_i,A)

print("A = \n",A)

L = 
 [[ 1.  0.  0.  0.]
 [-2.  1.  0.  0.]
 [ 1.  0.  1.  0.]
 [-2.  0.  0.  1.]]
L = 
 [[ 1.  0.  0.  0.]
 [-2.  1.  0.  0.]
 [ 1. -3.  1.  0.]
 [-2.  1.  0.  1.]]
L = 
 [[ 1.  0.  0.  0.]
 [-2.  1.  0.  0.]
 [ 1. -3.  1.  0.]
 [-2.  1. -3.  1.]]
A = 
 [[  2.   1.   2.   3.]
 [  0.   1.  -1.  -3.]
 [  0.   0.   1.   0.]
 [  0.   0.   0. -12.]]


In [53]:
def descomposicion_LU(A):
    """
    Realiza la descomposición LU de una matriz cuadrada A asumiendo que no es necesario realizar pivoteos
    Args:
        A (array): matriz cuadrada
    Return:
        L (array): matriz triangular inferior
        U (array): matriz triangular superior
    """
    A = np.array(A)
    n = A.shape[0]
    L = np.eye(n)
    for i in range(n-1):
        L_i = np.eye(n) # Me hago la L_{i} que va a hacer que la columna i de A sea 0 en la parte inferior

        for j in range(i+1,n):
            L[j,i] = -(A[j,i]/A[i,i]) # Los elementos de la matriz L son los multiplicadores de la eliminación de Gauss
            L_i[j,i] = -(A[j,i]/A[i,i])

        A = np.dot(L_i,A) # Actualizo A

    U = A
    return L,U


In [56]:
A= np.array([[2,1,2,3],
              [4,3,3,3],
              [-2,2,-4,-12],
              [4,1,8,-3]])

L,U = descomposicion_LU(A)
print("\nL = \n",L)
print("\nU = \n",U)


L = 
 [[ 1.  0.  0.  0.]
 [-2.  1.  0.  0.]
 [ 1. -3.  1.  0.]
 [-2.  1. -3.  1.]]

U = 
 [[  2.   1.   2.   3.]
 [  0.   1.  -1.  -3.]
 [  0.   0.   1.   0.]
 [  0.   0.   0. -12.]]
